# Generated by Django 6.0.1 on 2026-01-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document'),
    ]

    operations = [
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS vector;', 'DROP EXTENSION IF EXISTS vector;')
    ]
