# Generated by Django 6.0.1 on 2026-01-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_enable_vector_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding', models.JSONField()),
                ('document', models.ForeignKey(on_delete=models.CASCADE, related_name='chunks', to='api.document')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
    ]
