# Generated by Django 6.0.1 on 2026-01-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
