# Generated by Django 6.0.1 on 2026-01-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_document_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='referenced_in_messages', to='api.document'),
        ),
    ]
