# Generated by Django 6.0.1 on 2026-02-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_message_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
