# Generated by Django 6.0.1 on 2026-01-29 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_message_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
