# Generated by Django 6.0.1 on 2026-02-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_documentchunk_page_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentchunk',
            name='page_number',
        ),
        migrations.AlterField(
            model_name='documentchunk',
            name='chunk_index',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='api_documen_documen_08d005_idx'),
        ),
    ]
