# Generated by Django 6.0.1 on 2026-01-29 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_documentchunk'),
    ]

    operations = [
        migrations.RunSQL('DROP EXTENSION IF EXISTS vector;', 'CREATE EXTENSION IF NOT EXISTS vector;')
    ]
