# Generated by Django 6.0.1 on 2026-02-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='documentchunk',
            name='api_documen_documen_08d005_idx',
        ),
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
